import type { ExportPreset, FilenameTemplate, SonicSettings } from "./types";

export const BUILTIN_PRESETS: ExportPreset[] = [
  {
    id: "mp3Cbr320",
    name: "MP3 320",
    shortName: "MP3 320",
    description: "320 kbps constant-bitrate MP3",
    format: "mp3",
    extension: "mp3",
    bitrateKbps: 320,
    badge: "Share",
    isBuiltIn: true,
    lossy: true,
    supportsEmbeddedTags: true,
  },
  {
    id: "mp3V0",
    name: "MP3 V0",
    shortName: "MP3 V0",
    description: "Variable-bitrate MP3, typically 220–260 kbps",
    format: "mp3",
    extension: "mp3",
    badge: "Efficient",
    isBuiltIn: true,
    lossy: true,
    supportsEmbeddedTags: true,
  },
  {
    id: "wav44100S24",
    name: "WAV 44.1 / 24",
    shortName: "WAV 44.1",
    description: "24-bit, 44.1 kHz PCM for production sessions",
    format: "wav",
    extension: "wav",
    sampleRateHz: 44_100,
    bitDepth: 24,
    badge: "Studio",
    isBuiltIn: true,
    lossy: false,
    supportsEmbeddedTags: true,
  },
  {
    id: "wav48000S24",
    name: "WAV 48 / 24",
    shortName: "WAV 48",
    description: "24-bit, 48 kHz PCM for video and scoring sessions",
    format: "wav",
    extension: "wav",
    sampleRateHz: 48_000,
    bitDepth: 24,
    badge: "Studio",
    isBuiltIn: true,
    lossy: false,
    supportsEmbeddedTags: true,
  },
  {
    id: "m4aAac256",
    name: "M4A AAC 256",
    shortName: "M4A 256",
    description: "256 kbps AAC in an M4A container",
    format: "m4a",
    extension: "m4a",
    bitrateKbps: 256,
    badge: "Compact",
    isBuiltIn: true,
    lossy: true,
    supportsEmbeddedTags: true,
  },
  {
    id: "flac",
    name: "FLAC",
    shortName: "FLAC",
    description: "Lossless audio with embedded metadata",
    format: "flac",
    extension: "flac",
    badge: "Archive",
    isBuiltIn: true,
    lossy: false,
    supportsEmbeddedTags: true,
  },
  {
    id: "opus192",
    name: "Opus 192",
    shortName: "Opus 192",
    description: "192 kbps Opus audio",
    format: "opus",
    extension: "opus",
    bitrateKbps: 192,
    badge: "Modern",
    isBuiltIn: true,
    lossy: true,
    supportsEmbeddedTags: true,
  },
  {
    id: "original",
    name: "Original stream",
    shortName: "Original",
    description: "Keep the source format when possible; no conversion",
    format: "original",
    extension: "source",
    badge: "Fast",
    isBuiltIn: true,
    lossy: false,
    supportsEmbeddedTags: false,
  },
];

export const BUILTIN_TEMPLATES: FilenameTemplate[] = [
  {
    id: "title-metadata",
    name: "Title + musical details",
    template: "{title} — {bpm} BPM — {key}{detune}",
    isBuiltIn: true,
  },
  {
    id: "producer-title",
    name: "Producer first",
    template: "{producer} - {title} [{camelot}]",
    isBuiltIn: true,
  },
  {
    id: "compact-library",
    name: "Compact library",
    template: "{title}_{bpm}_{key}{detune}",
    isBuiltIn: true,
  },
];

export const DEFAULT_SETTINGS: SonicSettings = {
  defaultOutputDirectory: "",
  filenameTemplate: BUILTIN_TEMPLATES[0].template,
  defaultPresetId: "mp3Cbr320",
  defaultTemplateId: "title-metadata",
  maxConcurrentJobs: 1,
  historyEnabled: true,
  writeEmbeddedTags: true,
  includeSourcePathInSidecar: false,
  maxDurationMinutes: 30,
  maxInputBytes: 2 * 1024 * 1024 * 1024,
  queuePaused: false,
  previewSeconds: 30,
  confirmBeforeRemoving: true,
  templates: BUILTIN_TEMPLATES,
};
export const EMPTY_METADATA = {
  bpm: "",
  key: "",
  detuneCents: "",
};
